[package]
name = "splatmul"
version = "0.1.0"
edition = "2021"

[dependencies]
half = "2.4.1"
indicatif = { version = "0.17.8", features = ["rayon"] }
ndarray = "0.16.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
